// CraftDoc v2 — PDF & Word Export
// Uses jsPDF + html2canvas for PDF, docx.js for Word.
// Both libraries are loaded via CDN in index.html.

(function () {
  const WATERMARK = 'Generated by CraftDoc · effortlessdoc.com';

  function getTemplateLabel(tplId) {
    return window.CRAFTDOC_TEMPLATE_INDEX?.[tplId]?.label || tplId || 'Document';
  }

  // Build a hidden printable div
  function buildPrintContainer(text, cssClass) {
    const container = document.createElement('div');
    container.id = '__craftdoc_print__';
    // Inline critical styles so jsPDF / html2canvas sees them
    const style = document.createElement('style');
    style.textContent = document.getElementById('__tpl_css__')?.textContent || '';
    container.appendChild(style);
    const inner = document.createElement('div');
    inner.className = 'output-card ' + (cssClass || 'doc-essay');
    const pre = document.createElement('pre');
    pre.textContent = text;
    inner.appendChild(pre);
    const wm = document.createElement('div');
    wm.className = 'watermark';
    wm.textContent = WATERMARK;
    inner.appendChild(wm);
    container.appendChild(inner);
    document.body.appendChild(container);
    return container;
  }

  function removePrintContainer() {
    const c = document.getElementById('__craftdoc_print__');
    if (c) c.remove();
  }

  // ---- PDF ----
  async function toPDF(text, tplId) {
    if (typeof html2canvas === 'undefined' || typeof jspdf === 'undefined') {
      alert('PDF library not loaded. Please refresh and try again.');
      return;
    }
    const label = getTemplateLabel(tplId);
    const cssClass = window.CRAFTDOC_TEMPLATE_INDEX?.[tplId]?.css || 'doc-essay';
    const pc = buildPrintContainer(text, cssClass);

    try {
      const canvas = await html2canvas(pc, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff'
      });
      const { jsPDF } = jspdf;
      const pdf = new jsPDF({ unit: 'pt', format: 'a4', orientation: 'portrait' });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const imgW = pageW - 40; // 20pt margin each side
      const imgH = (canvas.height * imgW) / canvas.width;
      let y = 20;
      let remaining = imgH;
      let srcY = 0;

      while (remaining > 0) {
        const sliceH = Math.min(remaining, pageH - y);
        const sliceCanvas = document.createElement('canvas');
        sliceCanvas.width = canvas.width;
        sliceCanvas.height = (sliceH / imgW) * canvas.width;
        const ctx = sliceCanvas.getContext('2d');
        ctx.drawImage(canvas, 0, srcY, canvas.width, sliceCanvas.height, 0, 0, canvas.width, sliceCanvas.height);
        if (y > 20) pdf.addPage();
        pdf.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', 20, y, imgW, sliceH);
        y = 20;
        srcY += sliceCanvas.height;
        remaining -= sliceH;
      }

      // Footer watermark on last page
      pdf.setFontSize(8);
      pdf.setTextColor(180, 180, 180);
      pdf.text(WATERMARK, pageW / 2, pageH - 10, { align: 'center' });

      pdf.save(label.replace(/\s+/g, '_') + '.pdf');
    } finally {
      removePrintContainer();
    }
  }

  // ---- Word (.docx via docx.js) ----
  async function toWord(text, tplId) {
    if (typeof docx === 'undefined') {
      alert('Word library not loaded. Please refresh and try again.');
      return;
    }
    const label = getTemplateLabel(tplId);
    const cssClass = window.CRAFTDOC_TEMPLATE_INDEX?.[tplId]?.css || 'doc-essay';

    // Parse text into docx paragraphs (bold runs for headings; no custom Style class needed)
    const lines = text.split('\n');
    const children = [];

    for (const raw of lines) {
      const line = raw.trim();
      if (!line) {
        children.push(new docx.Paragraph({ text: '' }));
        continue;
      }
      // Section heading detection: ALL CAPS or lines ending with ':'
      const isHeading = (line === line.toUpperCase() && line.length > 3 && !line.includes('.')) || line.endsWith(':');

      if (isHeading) {
        children.push(new docx.Paragraph({
          spacing: { before: 200, after: 100 },
          children: [ new docx.TextRun({ text: line, bold: true, size: 28, color: '1E3A8A', font: 'Calibri' }) ]
        }));
      } else {
        children.push(new docx.Paragraph({
          spacing: { after: 80 },
          children: [ new docx.TextRun({ text: line, size: 22, font: 'Calibri' }) ]
        }));
      }
    }

    // Watermark paragraph
    children.push(new docx.Paragraph({ text: '' }));
    children.push(new docx.Paragraph({
      alignment: docx.AlignmentType.CENTER,
      spacing: { before: 200 },
      children: [ new docx.TextRun({ text: WATERMARK, size: 16, color: '999999', italics: true, font: 'Calibri' }) ]
    }));

    const doc = new docx.Document({
      sections: [{ properties: {}, children }]
    });

    const blob = await docx.Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = label.replace(/\s+/g, '_') + '.docx';
    a.click();
    URL.revokeObjectURL(url);
  }

  window.CraftDocExporter = { toPDF, toWord };
})();
